# Generated by Django 4.2.5 on 2024-04-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Dist_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.TextField()),
                ('property_id', models.CharField(max_length=255)),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('date', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Uspage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
        migrations.CreateModel(
            name='State_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.district_name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.state_name')),
            ],
        ),
        migrations.AddField(
            model_name='district_name',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.state_name'),
        ),
        migrations.CreateModel(
            name='Add_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.TextField()),
                ('property_id', models.CharField(max_length=255)),
                ('paragraph', models.TextField(default='none')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('price', models.CharField(default='None', max_length=255)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('Sold', 'Sold')], default='For Sale', max_length=50)),
                ('type', models.CharField(default='None', max_length=255)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.district_name')),
                ('images', models.ManyToManyField(related_name='properties', to='realrupees_app.propertyimage')),
                ('locality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.locality')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realrupees_app.state_name')),
            ],
        ),
    ]
